[package]
name = "http-serve"
version = "0.0.1"
authors = ["Scott Lamb <slamb@slamb.org>"]
license = "MIT/Apache-2.0"
readme = "../README.md"
description = "Conditional GET, HEAD, and byte range serving for abstract HTTP entities."
keywords = ["http", "file", "range"]
categories = ["web-programming::http-server"]

[badges]
travis-ci = { repository = "scottlamb/http-serve" }

[dependencies]
flate2 = "1.0"
futures = "0.1.7"
futures-cpupool = "0.1"
http = "0.1"
hyper = { version = "0.11", features = ["compat"] }
mime = "0.3"
smallvec = "0.6"
time = "0.1"
unicase = "2.1"

[dev-dependencies]
env_logger = "0.4"
futures-cpupool = "0.1"
lazy_static = "1.0"
leak = "0.1"
log = "0.4"
reqwest = "0.8"
tempdir = "0.3"
tokio-core = "0.1.6"

[profile.release]
debug = true
